version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: project-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: project-backend
    depends_on:
      - mongo
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
      - PORT=3000
    command: node src/server.js

  frontend:
    build: .
    container_name: project-frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    command: serve -s public -l 3001

volumes:
  mongo-data:
